<template>
    <nav-bar />
    <div class="container-fluid page-container text-center">
        <div class="row h-10 mb-5">
            <div class="col-md-12">
                <h1 class="mt-5"> Misuses and Plagarism</h1>
            </div>
        </div>

        <div ref="firstSection" class="row h-30 mb-5 justify-content-center" :class="{ 'hidden': !showFirstSection}">
        <div class="col-md-8 d-flex align-items-center">
          <div class="d-flex justify-content-center flex-wrap">
            <p class="section-text">
              Intentionally using LLMs like ChatGPT or Google Bard to generate essays, complete assignments, or to replace any other form of academic work is problematic for several reasons.
            </p>

            <p class="section-text">
              <span style="color: #6D0CFF;"><b> 1. Biases and Hallucinations: </b></span><br>
              LLMs can have biases and frequently generate inaccurate or nonsensical information, even making up non-existent sources for information. Relying on their output could lead to misinformation and misunderstanding of the topic.
            </p>

            <p class="section-text">
                <span style="color: #6D0CFF;"><b> 2. Academic Integrity: </b></span><br>
                Submitting generated content without proper attribution is a form of plagiarism, which is unethical and can lead to severe academic punishments. Using these models to complete assignments for you undermines the purpose of education, which is to develop critical thinking, research skills, and understanding of the subject. If you are completing assignments with LLMs rather than your own original work, you are missing the point of assignments, which is for you to learn from them.
            </p>

            <p class="section-text">
                <span style="color: #6D0CFF;"><b> 3. Detection Tools: </b></span><br>
                Educational institutions have begun to use tools like ZeroGPT to detect plagiarism and content generated by LLMs. These tools can detect AI-generated text with an accuracy rate of up to 98%, making it easy for educators to identify students who cheat (ZeroGPT, 2023). If you start to rely on ChatGPT to finish your assignments instead of learning to complete them yourself, it’s only a matter of time before you get caught. Using AI tools violates academic integrity and could result in harsh penalties. Is it really worth it?
            </p>
          </div>
        </div>
        <div class="col-md-4 d-flex align-items-center">
          <img class="img-a" src="../../../assets//dalle_page1_img.png" alt="an art piece depicting a purple swirl" />
        </div>
      </div>
    </div>


</template>

<script lang="ts">
import { defineComponent } from 'vue';
import NavBar from '../../reusable/nav-bar.vue';

export default defineComponent({
    name: 'ChatbotsPage4',
    components: {
        'nav-bar': NavBar,
    },
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap');

.container-fluid.page-container {
    height: 105vh;
    margin-top: 60px;
}

.text {
    font-size: 14px; /* Adjust the size as needed */
}

.section-text {
  width: 80%;
  text-align: left;
}

</style>