<template>
  <nav-bar />
  <module-navigation-bar :moduleName="'chatbots'" />
  <div id="main" class="container-fluid page-container text-center">
    <div class="row h-10 mb-5">
      <div class="col-md-12">
        <h1 class="tw-mt-24">Misuses and Plagiarism</h1>
      </div>
    </div>

    <div ref="firstSection" class="container h-30 mb-5 justify-content-center" :class="{ 'hidden': !showFirstSection }">

      <div class="row">
        <div class="col-md-8 d-flex align-items-center">
          <div class="d-flex justify-content-center flex-wrap">
            <p class="section-text">
              Intentionally using LLMs like ChatGPT or Google Bard to generate essays, complete assignments, or to replace
              any other form of academic work is problematic for several reasons.
            </p>

            <p class="section-text">
              <span style="color: #6D0CFF;"><b>1. Biases and Hallucinations:</b></span><br />
              LLMs can have biases and frequently generate inaccurate or nonsensical information, even making up
              non-existent sources for information. Relying on their output could lead to misinformation and
              misunderstanding of the topic.
            </p>

            <p class="section-text">
              <span style="color: #6D0CFF;"><b>2. Academic Integrity:</b></span><br />
              Submitting generated content without proper attribution is a form of plagiarism, which is unethical and can
              lead to severe academic punishments. Using these models to complete assignments for you undermines the
              purpose of education, which is to develop critical thinking, research skills, and understanding of the
              subject. If you are completing assignments with LLMs rather than your own work, you are missing the
              point of assignments, which is for you to learn from them.
            </p>
            <p class="section-text">
              It is important to note that using Generative AI tools may be permitted for some assignments. It is the
              responsibility of the student to check if it is permitted before using them. Sometimes, utilizing Generative
              AI tools can be a valuable resource to assist in your academic work, while other times it may not be
              appropriate. Make sure to adhere to your insitution's policies and guidelines regarding the use of
              Generative AI tools. You can refer to the University of Auckland's guidelines for students
              <a
                href="https://www.auckland.ac.nz/en/students/forms-policies-and-guidelines/student-policies-and-guidelines/academic-integrity-copyright/advice-for-student-on-using-generative-ai.html">here</a>.
            </p>

            <p class="section-text">
              <span style="color: #6D0CFF;"><b>3. Detection Tools:</b></span><br />
              Educational institutions have begun to use tools like ZeroGPT to detect plagiarism and content generated by
              LLMs. These tools can detect AI-generated text with an accuracy rate of up to 98%, making it easy for
              educators to identify students who cheat
              <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
                (ZeroGPT, 2023)
              </span>. If you start to rely on ChatGPT to finish your assignments instead of learning to
              complete them yourself, it’s only a matter of time before you get caught. Using AI tools violates academic
              integrity and could result in harsh penalties. Is it really worth it?
            </p>
          </div>
        </div>
        <div class="col-md-4 d-flex align-items-center justify-content-center pb-5">
          <img class="img-a" src="../../../assets/chatbots_page_4_a.jpeg"
            alt="a purple pop art depicting two students looking at their laptops" />
        </div>

      </div>
      <div class="row h-10">
        <div class="col-md-8 offset-md-4 d-flex justify-content-end align-items-left">
          <purple-btn :tag="'button'" v-if="!section1Completed" :text="'Continue'"
            @click="showSecondSection = true; scrollIntoSecondSection(); section1Completed = true;" />
        </div>
      </div>
    </div>

    <div ref="secondSection" class="container justify-content-center mb-5" :class="{ 'hidden': !showSecondSection }">
      <div class="row pb-5">
        <div class="col-md-12 d-flex justify-content-center align-items-center flex-wrap">
          <!-- Center content vertically and horizontally -->
          <h4 class="section-text pb-3">
            Here are some guidelines you can follow for using AI chatbots effectively:
          </h4>
          <p class="section-text purple-text">
            Guideline 1: Effective prompting
            <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
              (NSW Education, 2023)
            </span>.
          </p>
          <p class="section-text">
            A well-constructed prompt has the power to significantly enhance output quality while minimizing errors and
            irrelevant responses from generative AI tools.
          </p>

          <p class="section-text pb-4">
            When writing your prompt, provide clear roles and examples. This involves:
          </p>

          <div ref="firstPromptCard" class="guideline-example-container pb-4">
            <p class="section-text pb-1 purple-text">
              Defining a character and/or role for the AI tool
            </p>

            <div class="d-flex justify-content-between pb-3 flex-md-row flex-column">
              <quiz-ui-card
                :card-text="'Pretend you\'re an experienced short film director. Do you have any tips for going viral on tiktok ?'"
                :isNormal="false"></quiz-ui-card>
              <quiz-ui-card :isNormal="false" :isHappy="false"
                :card-text="'Do you have any tips for going viral on tiktok?'"></quiz-ui-card>
            </div>
            <purple-outline-btn v-if="!showSecondPromptCard" :text="'Next'"
              @click="showSecondPromptCard = true; scrollPage('secondPromptCard')"></purple-outline-btn>
          </div>

          <div ref="secondPromptCard" class="guideline-example-container pb-4"
            :class="{ 'hidden': !showSecondPromptCard }">
            <p class="section-text pb-1 purple-text">
              Giving a clear and unambiguous task
            </p>
            <div class="d-flex justify-content-between pb-3 flex-md-row flex-column">
              <quiz-ui-card
                :card-text="'Give me a unit conversion chart between the most common measures of length, from 10m to 100m in increments of 5m.'"
                :isNormal="false"></quiz-ui-card>
              <quiz-ui-card :isNormal="false" :isHappy="false"
                :card-text="'Give me a unit conversion chart.'"></quiz-ui-card>
            </div>
            <purple-outline-btn v-if="!showThirdPromptCard" :text="'Next'"
              @click="showThirdPromptCard = true; scrollPage('thirdPromptCard')"></purple-outline-btn>
          </div>

          <div ref="thirdPromptCard" class="guideline-example-container pb-4" :class="{ 'hidden': !showThirdPromptCard }">
            <p class="section-text pb-1 purple-text">
              Providing examples and additional guidelines
            </p>
            <div class="d-flex justify-content-between pb-3 flex-md-row flex-column">
              <quiz-ui-card
                :card-text="'Can I have a meal plan for the next week? Should have nutritious but quick-to-prepare dinners e.g. omelette.'"
                :isNormal="false">
              </quiz-ui-card>
              <quiz-ui-card :card-text="`Can I have a meal plan for the next week?`" :isNormal="false"
                :isHappy="false"></quiz-ui-card>
            </div>
            <purple-outline-btn v-if="!showFourthPromptCard" :text="'Next'"
              @click="showFourthPromptCard = true; scrollPage('fourthPromptCard')"></purple-outline-btn>
          </div>

          <div ref="fourthPromptCard" class="guideline-example-container pb-4"
            :class="{ 'hidden': !showFourthPromptCard }">
            <p class="section-text pb-1 purple-text">
              Specifying the output type
            </p>

            <div class="d-flex justify-content-between pb-3 flex-md-row flex-column">
              <quiz-ui-card :card-text="'What happened leading up to WWII? Bulleted list.'"
                :isNormal="false"></quiz-ui-card>
              <quiz-ui-card :card-text="`What happened leading up to WWII?`" :isNormal="false"
                :isHappy="false"></quiz-ui-card>
            </div>
            <purple-outline-btn v-if="!showFifthPromptCard" :text="'Next'"
              @click="showFifthPromptCard = true; scrollPage('fifthPromptCard')"></purple-outline-btn>
          </div>


          <div ref="fifthPromptCard" class="guideline-example-container pb-4" :class="{ 'hidden': !showFifthPromptCard }">
            <p class="section-text pb-1 purple-text">
              And being as elaborate as possible to improve the prompt
            </p>

            <div class="d-flex justify-content-between pb-3 flex-md-row flex-column align-items-center">
              <quiz-ui-card
                :card-text="`What's a synonym for 'dilate', but is like when a flower opens up? In the sense of getting wider or more expansive.?`"
                :isNormal="false"></quiz-ui-card>
              <quiz-ui-card :card-text="`What's a synonym for 'dilate'?`" :isNormal="false"
                :isHappy="false"></quiz-ui-card>
            </div>
            <purple-outline-btn v-if="!showThirdSection" :text="'Next'"
              @click="showThirdSection = true; scrollIntoThirdSection(); section2Completed = true;"></purple-outline-btn>
          </div>
        </div>
      </div>
    </div>

    <div ref="thirdSection" class="container mb-5" :class="{ 'hidden': !showThirdSection }">

      <div class="row">
        <div class="col-md-12 pb-5 d-flex justify-content-center flex-wrap">
          <p class="section-text purple-text">Guideline 2: Review and verify
            <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
              (Alston, 2023)
            </span>.
          </p>
          <p class="section-text">Remember that AI models still have the critical flaw of hallucinations, no matter how
            good your prompt is. So, whether you're asking about factual information, writing code, solving problems, or
            researching, take the time to verify each and every output. This issue is less prevalant in creative uses,
            such as writing a song, where the goal is to generate imaginative content rather than factual information.</p>
        </div>
        <div class="col pb-5">
          <img class="img-b" src="../../../assets/chatbots_page_4_b.jpeg"
            alt="2d illustration of students inspecting a book with magnifying glasses" />
        </div>
      </div>
      <div class="row h-20">
        <div class="col-md-12 d-flex justify-content-end">
          <purple-btn :tag="'button'" v-if="section2Completed && !section3Completed" :text="'Continue'"
            @click="showFourthSection = true; scrollIntoFourthSection(); section3Completed = true;" />
        </div>
      </div>

    </div>

    <div ref="fourthSection" class="container mb-5" :class="{ 'hidden': !showFourthSection }">
      <div class="row">
        <div class="col-md-12 pb-5 d-flex justify-content-center flex-wrap">
          <p class="section-text purple-text">Guideline 3: Keep your information private
            <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
              (ZeroGPT, 2023)
            </span>.
          </p>
          <p class="section-text">
            This one is hopefully self-explanatory. Remember that most publicly available AI models are still under
            development. AI models such as ChatGPT store and process your user data, including your conversations,
            location, and IP address.

            As you can see on the diagram, your prompts, part of your user data, may be collected to improve ChatGPT by
            adding it to its training data
            <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
              (OpenAI Help Center, n.d.)
            </span>. Human trainers can access all your user data. Don't enter any data that is sensitive, personal, or
            confidential.
          </p>
        </div>
        <div class="col pb-5">
          <img class="img-b mx-4" src="../../../assets/chatbots_page_4_c.jpeg"
            alt="2d illustration of a laptop behind a giant lock" />
          <img class="img-d mx-4" src="../../../assets/chatbots_page_4_d.png"
            alt="A flowchart diagram showing prompts augment the training data. The training data trains ChatGPT, which responds to prompts from user" />
        </div>
      </div>
      <div class="row h-20 pb-5">
        <div class="col-md-12 d-flex justify-content-end">
          <purple-btn :tag="'button'" v-if="section3Completed && !section4Completed" :text="'Continue'"
            @click="showFifthSection = true; scrollIntoFifthSection(); section4Completed = true;" />
        </div>
      </div>
    </div>

    <div ref="fifthSection" class="container mb-5" :class="{ 'hidden': !showFifthSection }">
      <div class="row">
        <div class="col-md-12 pb-5 d-flex justify-content-center flex-wrap">
          <p class="section-text purple-text">Guideline 4: Treat it as your tutor
            <span class="reference-link" @click="handleReferenceClick('misusesAndPlagrism')">
              (The University of Auckland, n.d.)
            </span>.
          </p>
          <p class="section-text">
            Once you have checked with your course directors that ChatGPT is allowed, here are some ways you can use
            ChatGPT to support your studies.<br>
          </p>
          <p class="section-text px-3">
            • Before you begin proper research, ask for an overview of your topic of interest.
          </p>
          <p class="section-text px-3">
            • Use it to break down solutions to problems in a way that helps you understand the thought process behind
            arriving at an answer.
          </p>
          <p class="section-text px-3">
            • Ask it to provide tips to improve your writing skills, including grammar, use of vocabulary, and sentence
            structure.
          </p>
          <p class="section-text">
          Treat ChatGPT as your tutor! The tutor assists students in solving problems but never gives them a direct solution. This analogy is helpful to remember if you use ChatGPT in your studies. Utilize ChatGPT to assist you in finding the solution, employing your effort just as you would when seeking guidance from a personal tutor.
          </p>
        </div>
        <div class="col pb-5">
          <img class="img-e mx-4" src="../../../assets/chatbots_page_4_e.jpeg"
            alt="colourful drawing of a woman holding notebooks, AI generated art" />
        </div>
      </div>
      <div class="row h-20 pb-5">
        <div class="col-md-12 d-flex justify-content-end">
          <router-link to="/chatbots/quiz">
            <purple-btn :text="'Continue'" @click="handlePageCompletionClick()" />
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'; // Import ref

import NavBar from '../../reusable/nav-bar.vue';
import ModuleNavigationBar from '../../reusable/module-navigation-bar.vue';
import PurpleBtn from '../../reusable-ui/purple-btn.vue';
import PurpleOutlineBtn from '../../reusable-ui/purple-btn-outline.vue';
import QuizUICard from '../../reusable/quiz-ui.vue';

export default defineComponent({
  name: 'ChatbotsPage4',
  data() {
    return {
      showFirstSection: true,
      showSecondSection: false,
      showThirdSection: false,
      showFourthSection: false,
      showFifthSection: false,
      showSecondPromptCard: false,
      showThirdPromptCard: false,
      showFourthPromptCard: false,
      showFifthPromptCard: false,
      section1Completed: false,
      section2Completed: false,
      section3Completed: false,
      section4Completed: false
    };
  },
  methods: {
    scrollIntoSecondSection() {
      this.$nextTick(() => {
        const element = this.$refs.secondSection as HTMLElement; // Changed to 'firstSection'
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'start',
          });
        }
      });
    },
    scrollIntoThirdSection() {
      this.$nextTick(() => {
        const element = this.$refs.thirdSection as HTMLElement;
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'start',
          });
        }
      });
    },
    scrollIntoFourthSection() {
      this.$nextTick(() => {
        const element = this.$refs.fourthSection as HTMLElement;
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'start',
          });
        }
      });
    },
    scrollIntoFifthSection() {
      this.$nextTick(() => {
        const element = this.$refs.fifthSection as HTMLElement;
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'start',
          });
        }
      });
    },
    scrollPage(ref: string) {
      this.$nextTick(() => {
        const element = this.$refs[ref] as HTMLElement;
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'start',
          });
        }
      });
    },
    handlePageCompletionClick(this: any) {
      this.$registerPageAsCompleted('chatbots', 'misuses-and-plagiarism');
    },
    handleReferenceClick(referenceSectionId: string) {
      const hash = `#${referenceSectionId}`;
      this.$router.push({ name: "references", hash });
    },
  },
  components: {
    'nav-bar': NavBar,
    'module-navigation-bar': ModuleNavigationBar,
    'purple-btn': PurpleBtn,
    'purple-outline-btn': PurpleOutlineBtn,
    'quiz-ui-card': QuizUICard,
  },
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap');

.container-fluid.page-container {
  height: 105vh;
  margin-top: 60px;
  margin-bottom: 20px;
}

.text {
  font-size: 14px;
  /* Adjust the size as needed */
}

.section-text {
  width: 60%;
  text-align: left;
  margin-bottom: 10px;
  /* Add margin between paragraphs */
}

.img-a {
  border-radius: 10px;
  margin-right: 10px;
  /* Reduce the margin-right to create less space */
  max-width: 100%;
  /* Ensure the image doesn't exceed its container width */
}

.img-b,
.img-c,
.img-e {
  width: 30%;
}

.img-d {
  width: 22%;
}

h2 {
  font-size: 25px;
}

.hidden {
  display: none;
  opacity: 0;
  max-height: 0;
  overflow: hidden;
}

.purple-text {
  color: #6D0CFF;
  font-weight: 600;
}

@media (max-width: 767.98px) {
  .section-text {
    width: 90%;
  }

  .img-a,
  .img-b,
  .img-c,
  .img-e {
    width: 80%;
  }

  .img-d {
    width: 80%;
  }
}
</style>
